# Pytorch exercises

In [150]:
import torch

Exercise 1: Write a PyTorch code to create a tensor of size (3, 3) filled with random values between 0 and 1.

In [151]:
tensor1 = torch.rand(3,3)
print(tensor1)

tensor([[0.4734, 0.6310, 0.2188],
        [0.2526, 0.5885, 0.0344],
        [0.7868, 0.7681, 0.2280]])


Exercise 2:
Create a tensor of size (5, 2) filled with zeros.

In [152]:
tensor2 = torch.ones(5,2)
print(tensor2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


Exercise 3:
Implement a PyTorch code to multiply two tensors of size (2, 3) and (3, 4) respectively.

In [153]:
tensor3_1 = torch.rand(2,3)
tensor3_2 = torch.rand(3,4)
tensor3 = torch.mm(tensor3_1, tensor3_2)
print(tensor3)

tensor([[0.6200, 0.5335, 0.2438, 1.1498],
        [0.6555, 0.9992, 0.3351, 1.3074]])


Exercise 4:
Create a PyTorch tensor with values ranging from 5 to 10.

In [154]:
tensor4 = torch.linspace(5, 10, 100)
print(tensor4)

tensor([ 5.0000,  5.0505,  5.1010,  5.1515,  5.2020,  5.2525,  5.3030,  5.3535,
         5.4040,  5.4545,  5.5051,  5.5556,  5.6061,  5.6566,  5.7071,  5.7576,
         5.8081,  5.8586,  5.9091,  5.9596,  6.0101,  6.0606,  6.1111,  6.1616,
         6.2121,  6.2626,  6.3131,  6.3636,  6.4141,  6.4646,  6.5152,  6.5657,
         6.6162,  6.6667,  6.7172,  6.7677,  6.8182,  6.8687,  6.9192,  6.9697,
         7.0202,  7.0707,  7.1212,  7.1717,  7.2222,  7.2727,  7.3232,  7.3737,
         7.4242,  7.4747,  7.5253,  7.5758,  7.6263,  7.6768,  7.7273,  7.7778,
         7.8283,  7.8788,  7.9293,  7.9798,  8.0303,  8.0808,  8.1313,  8.1818,
         8.2323,  8.2828,  8.3333,  8.3838,  8.4343,  8.4848,  8.5354,  8.5859,
         8.6364,  8.6869,  8.7374,  8.7879,  8.8384,  8.8889,  8.9394,  8.9899,
         9.0404,  9.0909,  9.1414,  9.1919,  9.2424,  9.2929,  9.3434,  9.3939,
         9.4444,  9.4949,  9.5455,  9.5960,  9.6465,  9.6970,  9.7475,  9.7980,
         9.8485,  9.8990,  9.9495, 10.00

Exercise 5:
Write a PyTorch code to compute the mean of a tensor.

In [155]:
# compute the mean of a tensor
mean = tensor4.mean()
print(mean)

tensor(7.5000)


Exercise 6:
Implement a PyTorch code to compute the element-wise product of two tensors of the same size.

In [156]:
tensor6_1 = torch.rand(3,3)
tensor6_2 = torch.rand(3,3)
tensor6 = torch.mul(tensor6_1, tensor6_2)
print(tensor6_1)
print(tensor6_2)
print(tensor6)

tensor([[0.7201, 0.8300, 0.0829],
        [0.8489, 0.2125, 0.7578],
        [0.2016, 0.4628, 0.1708]])
tensor([[0.5802, 0.7585, 0.0291],
        [0.9858, 0.0861, 0.7968],
        [0.5222, 0.3729, 0.7332]])
tensor([[0.4178, 0.6295, 0.0024],
        [0.8368, 0.0183, 0.6038],
        [0.1053, 0.1726, 0.1252]])


Exercise 7:
Create a PyTorch tensor with values sampled from a normal distribution with mean 0 and standard deviation 1.

In [157]:
tensor7 = torch.rand(3,3)
print(tensor7)

tensor([[0.9467, 0.2328, 0.9432],
        [0.1918, 0.3203, 0.4998],
        [0.7851, 0.6974, 0.2141]])


Exercise 8:
Write a PyTorch code to find the maximum value in a tensor.

In [158]:
# find the maximum value in a tensor
max_val = tensor7.max()
print(max_val)

tensor(0.9467)


Exercise 9:
Implement a PyTorch code to compute the cross entropy loss between predicted values and target values.

In [159]:
predicted = torch.rand(3,3)
target = torch.rand(3,3)
loss = torch.nn.functional.cross_entropy(predicted, target)
print(loss)


tensor(2.1459)


Exercise 10: Create a PyTorch tensor and then convert it to a NumPy array.

In [160]:
tensor10 = torch.rand(3,3)
print(tensor10)
numpy_array = tensor10.numpy()
print(numpy_array)


tensor([[0.5817, 0.3640, 0.6217],
        [0.7850, 0.2557, 0.4314],
        [0.2188, 0.3241, 0.8629]])
[[0.5816709  0.36401016 0.6217043 ]
 [0.7850225  0.25574678 0.4313851 ]
 [0.21878028 0.32407737 0.8629124 ]]


Exercise 11:
Write a PyTorch code to perform a matrix transpose operation on a tensor.

In [161]:
tensor11 = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

transposed_tensor11 = tensor11.t()
print(tensor11)
print(transposed_tensor11)


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


Exercise 12:
Implement a PyTorch code to concatenate two tensors along a specified dimension.

In [162]:
tensor12_1 = torch.tensor([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])
tensor12_2 = torch.tensor([[10, 11, 12],
                           [13, 14, 15],
                           [16, 17, 18]])
tensor12_rows = torch.cat((tensor12_1, tensor12_2), 0)
tensor12_columns = torch.cat((tensor12_1, tensor12_2), 1)

print(tensor12_rows)
print(tensor12_columns)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])
tensor([[ 1,  2,  3, 10, 11, 12],
        [ 4,  5,  6, 13, 14, 15],
        [ 7,  8,  9, 16, 17, 18]])


Exercise 13:
Create a PyTorch tensor and then convert it to a CUDA tensor if CUDA is available.

In [163]:
tensor13 = torch.rand(3,3)

if torch.cuda.is_available():
    cuda_tensor13 = tensor13.to('cuda')
    print("CUDA is available.")
    print(cuda_tensor13)
else:
    print("CUDA is not available.")
    print(tensor13)


CUDA is not available.
tensor([[0.1125, 0.4956, 0.4749],
        [0.3417, 0.9210, 0.6632],
        [0.1052, 0.1251, 0.1574]])


Exercise 14:
Write a PyTorch code to find the indices of non-zero elements in a tensor.

In [164]:
tensor14 = torch.tensor([[1, 0, 3],
                       [0, 0, 6],
                       [7, 8, 0]])

non_zero_tensor14 = torch.nonzero(tensor14)

print(tensor14)
print(non_zero_tensor14)


tensor([[1, 0, 3],
        [0, 0, 6],
        [7, 8, 0]])
tensor([[0, 0],
        [0, 2],
        [1, 2],
        [2, 0],
        [2, 1]])


Exercise 15:
Implement a PyTorch code to perform element-wise exponentiation on a tensor.

In [165]:
tensor15 = torch.tensor([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]])
exp_tensor15 = torch.exp(tensor15)
print(tensor15)
print(exp_tensor15)


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01],
        [5.4598e+01, 1.4841e+02, 4.0343e+02],
        [1.0966e+03, 2.9810e+03, 8.1031e+03]])


Exercise 16:
Create a PyTorch tensor and then reshape it into a tensor of different dimensions.

In [166]:
tensor16 = torch.tensor([[1, 2, 3, 4, 5, 6]])
tensor16_reshaped = tensor16.view(2, 3)
print(tensor16)
print(tensor16_reshaped)

tensor([[1, 2, 3, 4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])


Exercise 17:
Write a PyTorch code to compute the cosine similarity between two tensors.

In [167]:
import torch.nn.functional as F

tensor17_1 = torch.tensor([1.0, 2.0, 3.0])
tensor17_2 = torch.tensor([4.0, 5.0, 6.0])

tensor17_1 = tensor17_1.unsqueeze(0)
tensor17_2 = tensor17_2.unsqueeze(0)

cosine_tensor17 = F.cosine_similarity(tensor17_1, tensor17_2)
print(cosine_tensor17)

tensor([0.9746])


Exercise 18: Implement a PyTorch code to perform element-wise logarithm on a tensor.

In [168]:
tensor18 = torch.tensor([[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]])
log_tensor18 = torch.log(tensor18)
print(tensor18)
print(log_tensor18)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918],
        [1.9459, 2.0794, 2.1972]])


Exercise 19:
Create a PyTorch tensor and then calculate its standard deviation.

In [169]:
tensor19 = torch.tensor([[1.0, 2.0, 3.0],
                         [4.0, 5.0, 6.0],
                         [7.0, 8.0, 9.0]])
std_tensor19 = torch.std(tensor19)
print(tensor19)
print(std_tensor19)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor(2.7386)


Exercice 20: Write a PyTorch code to compute the Frobenius norm of a tensor.

In [170]:
tensor20 = torch.tensor([[1.0, 2.0, 3.0],
                         [4.0, 5.0, 6.0],
                         [7.0, 8.0, 9.0]])
frobenius_tensor20 = torch.norm(tensor20, p='fro')
print(tensor20)
print(frobenius_tensor20)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor(16.8819)
